name: Backend Checks

on:
  push:
  pull_request:

jobs:
  cpp-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show tool versions
        run: |
          git --version
          java -version
          g++ --version

      - name: Configure C++ engine
        run: |
          cd cpp_engine
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
      
      - name: Build C++ engine
        run: |
          cd cpp_engine/build
          cmake --build .

      - name: Run C++ engine on sample log
        run: |
          cd cpp_engine/build
          ./logAnalyser.exe ../tests/sample.log ../tests/format.json ../tests/result.json
          
      
      - name: Verify report was created
        run: |
          cd cpp_engine/build
          if (!(Test-Path ../tests/result.json)) { exit 1 }
          type ../tests/result.json
